### PR TITLE
Initial support for an EmbeddedStatic generator for purescript

### PR DESCRIPTION
**Pull request by wuzzeb**
Hi,

This is initial support for using the EmbeddedStatic subsite to compile purescript.  The advantage is that when compiling for production, the purescript is compiled, the resulting javascript is minified and then embedded into the resulting binary using template haskell.  Thus when executing, no compilation is performed and nothing needs to be distributed along with the binary.

It currently works very well in my limited testing on simple applications.  The main improvement I am going to look into is improving the debug mode.  Currently, every time the javascript is requested everything is recompiled which works but I expect will be slow for larger projects.  I would like to use the purescript make stuff to not have to recompile everything every single request during development.  (When compiling for production, of course we should recompile everything.)

### CODE REVIEW

**Comment by mpietrzak** [comment]
Looks awesome, although I have two comments:

1. Maybe it would be possible to extract and reuse `getRecursiveContents` and `compile` fns?

2. There's `yesodPureScript` Template Haskell function that actually does PureScript compilation "statically" if asked for.
   It has two modes controlled by first param:

   * dev mode is to recompile PureScript "dynamically" as needed if files are changed, without restarting/recompiling of the project (but still with caching of compilation results - so next requests are quite fast and there's no recompile on each request),
   * prod mode is to compile PureScript via TH during Haskell project compilation and give generated JS as String to Yesod's `toWidget`. It seems that by default `toWidget` results in files being auto-generated by Yesod into static subdirectory, but still: PureScript is compiled (and typechecked) statically (i.e. not at runtime) in this mode.

   So maybe it would be possible to make static-embedded part of this machinery (of prod mode)? So that I can somehow write "use foo.purs here" and: a) in dev mode I would get recompile-on-change-with-cache with pretty errors for quick dev/test/fix mode, and b) in prod mode - without any change in code, just by switching from dev mode to prod mode - I'd get compiled/typechecked and embedded PureScript?
   I'm not sure how to do that exactly, since if we want to use `toWidget`, then we don't have Route. And then if we don't want to use `toWidget`, the how do we add script *without* embedding it?
   Actually if we want to have both dev and prod mode with same API, then we can't use static routes (e.g. js_mypurescript_js), because in dev mode I want to be able to start dev server before creating first .purs file and yet the Yesod app should compile and start and just show me runtime error. If .purs file does not exist yet in dev mode, then GHC can't generate static routes. But that would be ok, because we'd still get compile-time integrity: even if .purs file is referenced by String, we'd still get compile time check, as the String would be handled by TH and GHC (in prod mode) would fail to find referenced file and would refuse to compile project with invalid .purs file reference…

Or maybe we should just move step by step and leave integration of EmbeddedStatic into yesodPureScript dual-mode machinery for later (as separate pull request), and for now have one API for dual-mode `yesodPureScript` approach and second for embedded static approach? For now, if really needed, users could still benefit from both by manually wrapping script reference in explicit "if dev" (until we provide nicer API).

What do you think?

**Comment by wuzzeb** [comment]
So I have been waiting for purescript 0.7 to come out to update this, and it was just released.  Purescript 0.7 has several changes which will change how this works.

For point 1, I plan on using the glob package which is how the purescript compiler itself works now.  So you can specify a glob of files.  Note that with purescript 0.7, foreign javascript will need globs too since it must live in separate files.

For the second, I should point out that using static routes is exactly how EmbeddedStatic works with separate dev and production modes.  The idea is that there is a single static route created ahead of time which will eventually contain all the generated javascript code.  During development, everything is recompiled every request and the modules which compile to the single javascript code file can change at any time and be based on which purescript files exist on disk at the time of the request (this is how the current pull request works).  Switching the cabal flag and compiling for production compiles the purescript at compile time, again based on what purs files are on disk.  Since other code references a static route, it automatically transfers between dev and production with no code changes at all.  This is exactly how my existing yesod-static-angular package works, you can add and remove files at any time during development which as you mention is very helpful.

I should probably put this nicer, but in my opinion your yesodPureScript TH should just be thrown away, since EmbeddedStatic does everything it does but with much more features like pre-compressing, using fast syscalls to serve (massive speedup in serving speed, like I measured over 20x speed imrpovement), avoiding multiple copies of the compressed code in memory since the ByteString is built right from the memory-mapped section of the executable where the embedding occurred.  And with the sendfile syscall, the resulting memory is sent directly by the kernel without being copied into user space at all.  The best part is all of these features we get for free since they are in the yesod-static package.  I don't really see any advantage to the existing TH stuff since all this already exists on the EmbeddedStatic side.

In the next few days I plan on updating to purescript 0.7 which will change the API.  I'll also start working on caching in dev mode, since it looks like purescript 0.7 has a nicer make mode, allowing us to re-use purescript itself for the caching.

**Comment by mpietrzak** [comment]
Nice, I wasn't aware that yesod-static is so powerful…

**Comment by mpietrzak** [comment]
Thank you for this PR and for explanation!

**Pull request merged**
